### ISSUE TITLE
403 OAuth provider error

### ISSUE THREAD

**Issue by Honzoraptor31415** [dishwasher-detergent/sprobble.xyz#26]
When you try to login, you'll be shown a json file saying:
`{"message":"User not registered in the Developer Dashboard","code":403,"type":"user_oauth2_provider_error","version":"0.12.129"}`.

*** Steps to reproduce ***

1. Navigate to https://www.sprobble.xyz/
2. Click the "Log In with Spotify" button

**Comment by dishwasher-detergent** [comment]
Ye /: I believe this is because my developer account is not in "production", and from what I understand it does violate some TOC of the api, so I can't get it approved.
